name: Create Release
on:
  push:
    paths:
      - 'build.py'
      - 'ReVanced-Extended-Builder.bat'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get next version
        id: next_version
        run: |
          LATEST_VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          NEXT_VERSION=$(echo $LATEST_VERSION | awk -F. '{OFS="."; $NF+=1; print}')
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1.12.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag: ${{ steps.next_version.outputs.version }}
          name: Release ${{ steps.next_version.outputs.version }}
          artifacts: ReVanced-Extended-Builder.bat