name: Create Release
on:
  push:
    paths:
      - 'build.py'
      - 'ReVanced-Extended-Builder.bat'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.4.1
        with:
          fetch-depth: 0
      - name: Get next version
        id: next_version
        run: |
          LATEST_VERSION=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          NEXT_VERSION=$(echo $LATEST_VERSION | awk -F. '{OFS="."; $NF+=1; print}')
          echo "version=$NEXT_VERSION" >> $GITHUB_OUTPUT
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1.1.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.next_version.outputs.version }}
          release_name: Release ${{ steps.next_version.outputs.version }}
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ReVanced-Extended-Builder.bat
          asset_name: ReVanced-Extended-Builder.bat
          asset_content_type: application/octet-stream